# Simulation avec FBA

In [2]:
import pandas
pandas.options.display.max_rows = 100

import cobra
from cobra.io import load_model # type: ignore

model = load_model("textbook")

Voir les composants du réseau métabolique:
- Métabolites: `model.metabolites`
- Réactions: `model.reactions`
- Gènes: `model.genes`

In [3]:
print(len(model.reactions))
print(len(model.metabolites))
print(len(model.genes))

95
72
137

Sous Jupyter Notebook, ce type d'info est stocké sous forme de tableau, ce qui est plus lisible.

In [4]:
model

## 1. Création du modèle à partir de ralsto_metexplore3.xml

In [5]:
# Chargement du fichier SBML
from cobra.io import read_sbml_model # type: ignore
model_ralsto = read_sbml_model("ralsto_metexplore3.xml")

Adding exchange reaction EX_hdcea_b with default bounds for boundary metabolite: hdcea_b.
Adding exchange reaction EX_RSc1944_b with default bounds for boundary metabolite: RSc1944_b.
Adding exchange reaction EX_3oochslac_b with default bounds for boundary metabolite: 3oochslac_b.
Adding exchange reaction EX_glu_D_b with default bounds for boundary metabolite: glu_D_b.
Adding exchange reaction EX_RipS4_b with default bounds for boundary metabolite: RipS4_b.
Adding exchange reaction EX_fecrm_b with default bounds for boundary metabolite: fecrm_b.
Adding exchange reaction EX_ni2_b with default bounds for boundary metabolite: ni2_b.
Adding exchange reaction EX_RipK_b with default bounds for boundary metabolite: RipK_b.
Adding exchange reaction EX_berb_b with default bounds for boundary metabolite: berb_b.
Adding exchange reaction EX_tartr_L_b with default bounds for boundary metabolite: tartr_L_b.
Adding exchange reaction EX_octa_b with default bounds for boundary metabolite: octa_b.
Adding exchange reaction EX_orn_b with default bounds for boundary metabolite: orn_b.
Adding exchange reaction EX_34dhphe_b with default bounds for boundary metabolite: 34dhphe_b.
Adding exchange reaction EX_tungs_b with default bounds for boundary metabolite: tungs_b.
Adding exchange reaction EX_RSp0295_act_b with default bounds for boundary metabolite: RSp0295_act_b.
Adding exchange reaction EX_PehB_b with default bounds for boundary metabolite: PehB_b.
Adding exchange reaction EX_g3pi_b with default bounds for boundary metabolite: g3pi_b.
Adding exchange reaction EX_gthox_b with default bounds for boundary metabolite: gthox_b.
Adding exchange reaction EX_RSp0629_b with default bounds for boundary metabolite: RSp0629_b.
Adding exchange reaction EX_RipAX2_b with default bounds for boundary metabolite: RipAX2_b.
Adding exchange reaction EX_mg2_b with default bounds for boundary metabolite: mg2_b.
Adding exchange reaction EX_RipX_b with default bounds for boundary metabolite: RipX_b.
Adding exchange reaction EX_RipAI_b with default bounds for boundary metabolite: RipAI_b.
Adding exchange reaction EX_cafe_b with default bounds for boundary metabolite: cafe_b.
Adding exchange reaction EX_hslac_b with default bounds for boundary metabolite: hslac_b.
Adding exchange reaction EX_RipG1_b with default bounds for boundary metabolite: RipG1_b.
Adding exchange reaction EX_RSp0518_b with default bounds for boundary metabolite: RSp0518_b.
Adding exchange reaction EX_5oxpro_b with default bounds for boundary metabolite: 5oxpro_b.
Adding exchange reaction EX_ac_b with default bounds for boundary metabolite: ac_b.
Adding exchange reaction EX_met_L_ala_L_b with default bounds for boundary metabolite: met_L_ala_L_b.
Adding exchange reaction EX_RipAV_b with default bounds for boundary metabolite: RipAV_b.
Adding exchange reaction EX_chtbs_b with default bounds for boundary metabolite: chtbs_b.
Adding exchange reaction EX_arbtnl_fe3_b with default bounds for boundary metabolite: arbtnl_fe3_b.
Adding exchange reaction EX_ddca_b with default bounds for boundary metabolite: ddca_b.
Adding exchange reaction EX_galur3u_b with default bounds for boundary metabolite: galur3u_b.
Adding exchange reaction EX_orot_b with default bounds for boundary metabolite: orot_b.
Adding exchange reaction EX_RSp0540_b with default bounds for boundary metabolite: RSp0540_b.
Adding exchange reaction EX_glcr_b with default bounds for boundary metabolite: glcr_b.
Adding exchange reaction EX_RSc0102_act_b with default bounds for boundary metabolite: RSc0102_act_b.
Adding exchange reaction EX_pa181_b with default bounds for boundary metabolite: pa181_b.
Adding exchange reaction EX_his_L_b with default bounds for boundary metabolite: his_L_b.
Adding exchange reaction EX_mepyr_b with default bounds for boundary metabolite: mepyr_b.
Adding exchange reaction EX_2hyoxplac_b with default bounds for boundary metabolite: 2hyoxplac_b.
Adding exchange reaction EX_Egl_b with default bounds for boundary metabolite: Egl_b.
Adding exchange reaction EX_g3pe_b with default bounds for boundary metabolite: g3pe_b.
Adding exchange reaction EX_cys_L_b with default bounds for boundary metabolite: cys_L_b.
Adding exchange reaction EX_no2r_b with default bounds for boundary metabolite: no2r_b.
Adding exchange reaction EX_RipT_b with default bounds for boundary metabolite: RipT_b.
Adding exchange reaction EX_RipU2_b with default bounds for boundary metabolite: RipU2_b.
Adding exchange reaction EX_n2_b with default bounds for boundary metabolite: n2_b.
Adding exchange reaction EX_pc181_b with default bounds for boundary metabolite: pc181_b.
Adding exchange reaction EX_RipAE_b with default bounds for boundary metabolite: RipAE_b.
Adding exchange reaction EX_RipA4_b with default bounds for boundary metabolite: RipA4_b.
Adding exchange reaction EX_resoc_b with default bounds for boundary metabolite: resoc_b.
Adding exchange reaction EX_RipAR_b with default bounds for boundary metabolite: RipAR_b.
Adding exchange reaction EX_RSp0630_b with default bounds for boundary metabolite: RSp0630_b.
Adding exchange reaction EX_PCW_RSp1545_LPS_b with default bounds for boundary metabolite: PCW_RSp1545_LPS_b.
Adding exchange reaction EX_ch4s_b with default bounds for boundary metabolite: ch4s_b.
Adding exchange reaction EX_RipV1_b with default bounds for boundary metabolite: RipV1_b.
Adding exchange reaction EX_RipB_b with default bounds for boundary metabolite: RipB_b.
Adding exchange reaction EX_cana_L_b with default bounds for boundary metabolite: cana_L_b.
Adding exchange reaction EX_cbl1_b with default bounds for boundary metabolite: cbl1_b.
Adding exchange reaction EX_pc160_b with default bounds for boundary metabolite: pc160_b.
Adding exchange reaction EX_RSc0887_b with default bounds for boundary metabolite: RSc0887_b.
Adding exchange reaction EX_quin_kt_b with default bounds for boundary metabolite: quin_kt_b.
Adding exchange reaction EX_ocdcea_b with default bounds for boundary metabolite: ocdcea_b.
Adding exchange reaction EX_fusar_b with default bounds for boundary metabolite: fusar_b.
Adding exchange reaction EX_cu2_b with default bounds for boundary metabolite: cu2_b.
Adding exchange reaction EX_23cgmp_b with default bounds for boundary metabolite: 23cgmp_b.
Adding exchange reaction EX_indpyr_b with default bounds for boundary metabolite: indpyr_b.
Adding exchange reaction EX_23camp_b with default bounds for boundary metabolite: 23camp_b.
Adding exchange reaction EX_gthrd_b with default bounds for boundary metabolite: gthrd_b.
Adding exchange reaction EX_L_dpchrm_b with default bounds for boundary metabolite: L_dpchrm_b.
Adding exchange reaction EX_3hcinnm_b with default bounds for boundary metabolite: 3hcinnm_b.
Adding exchange reaction EX_PCW_D_Mannose_b with default bounds for boundary metabolite: PCW_D_Mannose_b.
Adding exchange reaction EX_pect_b with default bounds for boundary metabolite: pect_b.
Adding exchange reaction EX_hpa_b with default bounds for boundary metabolite: hpa_b.
Adding exchange reaction EX_asp_L_glu_L_b with default bounds for boundary metabolite: asp_L_glu_L_b.
Adding exchange reaction EX_selt_b with default bounds for boundary metabolite: selt_b.
Adding exchange reaction EX_succ_b with default bounds for boundary metabolite: succ_b.
Adding exchange reaction EX_RipAA_b with default bounds for boundary metabolite: RipAA_b.
Adding exchange reaction EX_ala_L_glu_L_b with default bounds for boundary metabolite: ala_L_glu_L_b.
Adding exchange reaction EX_gal_b with default bounds for boundary metabolite: gal_b.
Adding exchange reaction EX_cro4_b with default bounds for boundary metabolite: cro4_b.
Adding exchange reaction EX_RipAN_b with default bounds for boundary metabolite: RipAN_b.
Adding exchange reaction EX_RipG6_b with default bounds for boundary metabolite: RipG6_b.
Adding exchange reaction EX_5drib_b with default bounds for boundary metabolite: 5drib_b.
Adding exchange reaction EX_zn2_b with default bounds for boundary metabolite: zn2_b.
Adding exchange reaction EX_EPS_b with default bounds for boundary metabolite: EPS_b.
Adding exchange reaction EX_RSp0175_b with default bounds for boundary metabolite: RSp0175_b.
Adding exchange reaction EX_isetac_b with default bounds for boundary metabolite: isetac_b.
Adding exchange reaction EX_but_b with default bounds for boundary metabolite: but_b.
Adding exchange reaction EX_pencil_b with default bounds for boundary metabolite: pencil_b.
Adding exchange reaction EX_dha_b with default bounds for boundary metabolite: dha_b.
Adding exchange reaction EX_4hba_b with default bounds for boundary metabolite: 4hba_b.
Adding exchange reaction EX_12dgr160_b with default bounds for boundary metabolite: 12dgr160_b.
Adding exchange reaction EX_sbt_D_b with default bounds for boundary metabolite: sbt_D_b.
Adding exchange reaction EX_pa141_b with default bounds for boundary metabolite: pa141_b.
Adding exchange reaction EX_RSp1466_b with default bounds for boundary metabolite: RSp1466_b.
Adding exchange reaction EX_ochslac_b with default bounds for boundary metabolite: ochslac_b.
Adding exchange reaction EX_23ccmp_b with default bounds for boundary metabolite: 23ccmp_b.
Adding exchange reaction EX_aso3_b with default bounds for boundary metabolite: aso3_b.
Adding exchange reaction EX_pc120_b with default bounds for boundary metabolite: pc120_b.
Adding exchange reaction EX_RSp1444_b with default bounds for boundary metabolite: RSp1444_b.
Adding exchange reaction EX_RSp0295_b with default bounds for boundary metabolite: RSp0295_b.
Adding exchange reaction EX_novbcn_b with default bounds for boundary metabolite: novbcn_b.
Adding exchange reaction EX_RSp0745_b with default bounds for boundary metabolite: RSp0745_b.
Adding exchange reaction EX_ampica_b with default bounds for boundary metabolite: ampica_b.
Adding exchange reaction EX_RipO1_b with default bounds for boundary metabolite: RipO1_b.
Adding exchange reaction EX_val_L_b with default bounds for boundary metabolite: val_L_b.
Adding exchange reaction EX_cytd_b with default bounds for boundary metabolite: cytd_b.
Adding exchange reaction EX_pro_L_b with default bounds for boundary metabolite: pro_L_b.
Adding exchange reaction EX_RipAJ_b with default bounds for boundary metabolite: RipAJ_b.
Adding exchange reaction EX_RSc0104_b with default bounds for boundary metabolite: RSc0104_b.
Adding exchange reaction EX_3oocta_b with default bounds for boundary metabolite: 3oocta_b.
Adding exchange reaction EX_RSc0249_act_b with default bounds for boundary metabolite: RSc0249_act_b.
Adding exchange reaction EX_asn_L_b with default bounds for boundary metabolite: asn_L_b.
Adding exchange reaction EX_bromosucc_b with default bounds for boundary metabolite: bromosucc_b.
Adding exchange reaction EX_RipG2_b with default bounds for boundary metabolite: RipG2_b.
Adding exchange reaction EX_tzea_b with default bounds for boundary metabolite: tzea_b.
Adding exchange reaction EX_pac_b with default bounds for boundary metabolite: pac_b.
Adding exchange reaction EX_ocdca_b with default bounds for boundary metabolite: ocdca_b.
Adding exchange reaction EX_PglA_b with default bounds for boundary metabolite: PglA_b.
Adding exchange reaction EX_RipS5_b with default bounds for boundary metabolite: RipS5_b.
Adding exchange reaction EX_met_L_b with default bounds for boundary metabolite: met_L_b.
Adding exchange reaction EX_h2o2_b with default bounds for boundary metabolite: h2o2_b.
Adding exchange reaction EX_phe_L_b with default bounds for boundary metabolite: phe_L_b.
Adding exchange reaction EX_PCW_RSp1180_act_pili_b with default bounds for boundary metabolite: PCW_RSp1180_act_pili_b.
Adding exchange reaction EX_RipY_b with default bounds for boundary metabolite: RipY_b.
Adding exchange reaction EX_ins_b with default bounds for boundary metabolite: ins_b.
Adding exchange reaction EX_tre_b with default bounds for boundary metabolite: tre_b.
Adding exchange reaction EX_RSc0958_b with default bounds for boundary metabolite: RSc0958_b.
Adding exchange reaction EX_pa160_b with default bounds for boundary metabolite: pa160_b.
Adding exchange reaction EX_hdca_b with default bounds for boundary metabolite: hdca_b.
Adding exchange reaction EX_Rsl_b with default bounds for boundary metabolite: Rsl_b.
Adding exchange reaction EX_polygalurnxu_b with default bounds for boundary metabolite: polygalurnxu_b.
Adding exchange reaction EX_mesucc_b with default bounds for boundary metabolite: mesucc_b.
Adding exchange reaction EX_etha_b with default bounds for boundary metabolite: etha_b.
Adding exchange reaction EX_tyr_L_b with default bounds for boundary metabolite: tyr_L_b.
Adding exchange reaction EX_pc180_b with default bounds for boundary metabolite: pc180_b.
Adding exchange reaction EX_RipA5_b with default bounds for boundary metabolite: RipA5_b.
Adding exchange reaction EX_RSp0103_b with default bounds for boundary metabolite: RSp0103_b.
Adding exchange reaction EX_fe2_b with default bounds for boundary metabolite: fe2_b.
Adding exchange reaction EX_nh4_b with default bounds for boundary metabolite: nh4_b.
Adding exchange reaction EX_ohr_b with default bounds for boundary metabolite: ohr_b.
Adding exchange reaction EX_3ohpame_b with default bounds for boundary metabolite: 3ohpame_b.
Adding exchange reaction EX_RipS1_b with default bounds for boundary metabolite: RipS1_b.
Adding exchange reaction EX_RipH1_b with default bounds for boundary metabolite: RipH1_b.
Adding exchange reaction EX_fer_b with default bounds for boundary metabolite: fer_b.
Adding exchange reaction EX_fecrm_un_b with default bounds for boundary metabolite: fecrm_un_b.
Adding exchange reaction EX_gly_gln_L_b with default bounds for boundary metabolite: gly_gln_L_b.
Adding exchange reaction EX_RipAW_b with default bounds for boundary metabolite: RipAW_b.
Adding exchange reaction EX_ralf_b with default bounds for boundary metabolite: ralf_b.
Adding exchange reaction EX_pept_b with default bounds for boundary metabolite: pept_b.
Adding exchange reaction EX_ser_L_b with default bounds for boundary metabolite: ser_L_b.
Adding exchange reaction EX_hom_L_b with default bounds for boundary metabolite: hom_L_b.
Adding exchange reaction EX_RSp0881_b with default bounds for boundary metabolite: RSp0881_b.
Adding exchange reaction EX_DNAf_30kb_b with default bounds for boundary metabolite: DNAf_30kb_b.
Adding exchange reaction EX_cellb_b with default bounds for boundary metabolite: cellb_b.
Adding exchange reaction EX_gly_b with default bounds for boundary metabolite: gly_b.
Adding exchange reaction EX_o2_b with default bounds for boundary metabolite: o2_b.
Adding exchange reaction EX_lpd_lpd_b with default bounds for boundary metabolite: lpd_lpd_b.
Adding exchange reaction EX_RipAZ1_b with default bounds for boundary metabolite: RipAZ1_b.
Adding exchange reaction EX_esclt_b with default bounds for boundary metabolite: esclt_b.
Adding exchange reaction EX_im4ac_b with default bounds for boundary metabolite: im4ac_b.
Adding exchange reaction EX_RipD_b with default bounds for boundary metabolite: RipD_b.
Adding exchange reaction EX_mincyc_b with default bounds for boundary metabolite: mincyc_b.
Adding exchange reaction EX_cellos_Expansin_LPS_b with default bounds for boundary metabolite: cellos_Expansin_LPS_b.
Adding exchange reaction EX_hepthslac_b with default bounds for boundary metabolite: hepthslac_b.
Adding exchange reaction EX_iad_b with default bounds for boundary metabolite: iad_b.
Adding exchange reaction EX_4hbz_b with default bounds for boundary metabolite: 4hbz_b.
Adding exchange reaction EX_galt_b with default bounds for boundary metabolite: galt_b.
Adding exchange reaction EX_glu_L_b with default bounds for boundary metabolite: glu_L_b.
Adding exchange reaction EX_frmd_b with default bounds for boundary metabolite: frmd_b.
Adding exchange reaction EX_RSc3220_b with default bounds for boundary metabolite: RSc3220_b.
Adding exchange reaction EX_RipAB_b with default bounds for boundary metabolite: RipAB_b.
Adding exchange reaction EX_chitos_b with default bounds for boundary metabolite: chitos_b.
Adding exchange reaction EX_glyclt_b with default bounds for boundary metabolite: glyclt_b.
Adding exchange reaction EX_RipA1_b with default bounds for boundary metabolite: RipA1_b.
Adding exchange reaction EX_PS_PGA_b with default bounds for boundary metabolite: PS_PGA_b.
Adding exchange reaction EX_rfamp_b with default bounds for boundary metabolite: rfamp_b.
Adding exchange reaction EX_thm_b with default bounds for boundary metabolite: thm_b.
Adding exchange reaction EX_RipAS_b with default bounds for boundary metabolite: RipAS_b.
Adding exchange reaction EX_12dgr161_b with default bounds for boundary metabolite: 12dgr161_b.
Adding exchange reaction EX_dextrin_b with default bounds for boundary metabolite: dextrin_b.
Adding exchange reaction EX_ttrcyc_b with default bounds for boundary metabolite: ttrcyc_b.
Adding exchange reaction EX_fum_b with default bounds for boundary metabolite: fum_b.
Adding exchange reaction EX_crn_b with default bounds for boundary metabolite: crn_b.
Adding exchange reaction EX_thr_L_b with default bounds for boundary metabolite: thr_L_b.
Adding exchange reaction EX_ttdcea_b with default bounds for boundary metabolite: ttdcea_b.
Adding exchange reaction EX_RipBA_b with default bounds for boundary metabolite: RipBA_b.
Adding exchange reaction EX_mccdn_b with default bounds for boundary metabolite: mccdn_b.
Adding exchange reaction EX_PCW_RSc0102_act_b with default bounds for boundary metabolite: PCW_RSc0102_act_b.
Adding exchange reaction EX_PCW_L_Fucose_Rsl_b with default bounds for boundary metabolite: PCW_L_Fucose_Rsl_b.
Adding exchange reaction EX_no_b with default bounds for boundary metabolite: no_b.
Adding exchange reaction EX_galctn_D_b with default bounds for boundary metabolite: galctn_D_b.
Adding exchange reaction EX_fe3_b with default bounds for boundary metabolite: fe3_b.
Adding exchange reaction EX_Prot_b with default bounds for boundary metabolite: Prot_b.
Adding exchange reaction EX_pyr_b with default bounds for boundary metabolite: pyr_b.
Adding exchange reaction EX_asp_L_b with default bounds for boundary metabolite: asp_L_b.
Adding exchange reaction EX_PCW_RSc0104_act_b with default bounds for boundary metabolite: PCW_RSc0104_act_b.
Adding exchange reaction EX_nac_b with default bounds for boundary metabolite: nac_b.
Adding exchange reaction EX_pa120_b with default bounds for boundary metabolite: pa120_b.
Adding exchange reaction EX_h_b with default bounds for boundary metabolite: h_b.
Adding exchange reaction EX_3hpp_b with default bounds for boundary metabolite: 3hpp_b.
Adding exchange reaction EX_RipAO_b with default bounds for boundary metabolite: RipAO_b.
Adding exchange reaction EX_PCW_RSp0295_act_b with default bounds for boundary metabolite: PCW_RSp0295_act_b.
Adding exchange reaction EX_RSc3188_b with default bounds for boundary metabolite: RSc3188_b.
Adding exchange reaction EX_acfv_b with default bounds for boundary metabolite: acfv_b.
Adding exchange reaction EX_pc141_b with default bounds for boundary metabolite: pc141_b.
Adding exchange reaction EX_pbhb_b with default bounds for boundary metabolite: pbhb_b.
Adding exchange reaction EX_RipG7_b with default bounds for boundary metabolite: RipG7_b.
Adding exchange reaction EX_PlcN_b with default bounds for boundary metabolite: PlcN_b.
Adding exchange reaction EX_PCW_RSp0294_act_b with default bounds for boundary metabolite: PCW_RSp0294_act_b.
Adding exchange reaction EX_RSp1180_b with default bounds for boundary metabolite: RSp1180_b.
Adding exchange reaction EX_RipS6_b with default bounds for boundary metabolite: RipS6_b.
Adding exchange reaction EX_RSp0294_b with default bounds for boundary metabolite: RSp0294_b.
Adding exchange reaction EX_RipE1_b with default bounds for boundary metabolite: RipE1_b.

In [6]:
model_ralsto

### 2. Nombre de réactions, métabolites et gènes dans le modèle Ralstonia solanacearum

In [7]:
# Verification du modèle
print("Nombre de reactions: ", len(model_ralsto.reactions))
print("Nombre de métabolites: ", len(model_ralsto.metabolites))
print("Nombre de gènes:", len(model_ralsto.genes))

Nombre de reactions:  3097
Nombre de métabolites:  2574
Nombre de gènes: 2219

In [38]:
with open("reactions_list_cobra_ralsto_metexplore_3.csv", 'w') as f:
    f.write("ReactionID,Equation\n")
    for r in model_ralsto.reactions:
        f.write(f"{r.id},{r.reaction}\n")

### 3. Indication de la fonction objectif ==> BIOMASS

In [10]:
# Vérifier les identifiants des réactions
print([r.id for r in model_ralsto.reactions[:10]])  # affiche les 10 premières réactions qui n'ont pas le R_

['EX_hdcea_b', 'EX_RSc1944_b', 'EX_3oochslac_b', 'EX_glu_D_b', 'EX_RipS4_b', 'EX_fecrm_b', 'EX_ni2_b', 'EX_RipK_b', 'EX_berb_b', 'EX_tartr_L_b']

In [11]:
biomass_rxn = model_ralsto.reactions.get_by_id("BIOMASS")
print("Biomass reaction:", biomass_rxn)
model_ralsto.objective = biomass_rxn
print("Objectif actuel:\n",model_ralsto.objective)

Biomass reaction: BIOMASS: 0.000223 10fthf_c + 2.6e-05 2fe2s_c + 0.00026 4fe4s_c + 0.01068 Oantigen_core_kdo_lipidA_RS_e + 0.0094 acglucan_p + 0.000223 adocbl_c + 0.6411 alatrna_c + 0.000223 amet_c + 0.24141 argtrna_c + 0.19535 asntrna_c + 0.19535 asptrna_c + 54.832741 atp_c + 2e-06 btn_c + 0.000223 chor_c + 0.005205 cl_c + 0.00353 clpn160_p + 0.0021 clpn161_p + 0.00087 clpn180_p + 0.00162 clpn181_p + 0.000576 coa_c + 2.5e-05 cobalt2_c + 0.22995 ctp_c + 0.06088 cystrna_c + 0.01689 datp_c + 0.03425 dctp_c + 0.03425 dgtp_c + 0.01689 dttp_c + 0.000223 fad_c + 0.006715 fe2_c + 0.27105 glntrna_c + 0.016 glucan_p + 0.27105 glutrna_c + 0.009513 glycogen_c + 0.60087 glytrna_c + 0.000223 gthrd_c + 0.21053 gtp_c + 54.72405 h2o_c + 0.000223 hemeO_c + 0.11806 histrna_c + 0.162 iletrna_c + 0.195193 k_c + 0.27635 leutrna_c + 3e-06 lipopb_c + 0.10006 lystrna_c + 0.08417 mettrna_c + 0.008675 mg2_c + 0.000223 mlthf_c + 0.000691 mn2_c + 7e-06 mobd_c + 0.000122 mocogdp_c + 0.00323 murein3p3p_p + 0.00145 murein3px4p_p + 0.01291 murein4p4p_p + 0.01308 murein4px4p_p + 0.00161 murein4px4px4p_p + 0.001831 nad_c + 0.000447 nadp_c + 0.013013 nh4_c + 0.01791 pe160_c + 0.01066 pe161_c + 0.0044 pe180_c + 0.00821 pe181_c + 0.0057 pg160_c + 0.00339 pg161_c + 0.0014 pg180_c + 0.00261 pg181_c + 0.000223 pheme_c + 0.22764 phetrna_c + 0.52781 protrna_c + 0.03327 ptrc_c + 0.000223 pydx5p_c + 0.000223 q8h2_c + 0.000223 ribflv_c + 0.22288 sertrna_c + 0.004338 so4_c + 0.006744 spmd_c + 0.000223 thf_c + 0.000223 thmpp_c + 0.40446 thrtrna_c + 0.00424 trptrna_c + 0.11753 tyrtrna_c + 5.5e-05 udcpdp_c + 0.08612 utp_c + 0.3637 valtrna_c --> 54.72405 adp_c + 54.72405 h_c + 54.72405 pi_c + 0.737561 ppi_c + 0.6411 trnaala_c + 0.24141 trnaarg_c + 0.3907 trnaasp_c + 0.06088 trnacys_c + 0.27105 trnagln_c + 0.27105 trnaglu_c + 0.60087 trnagly_c + 0.11806 trnahis_c + 0.162 trnaile_c + 0.27635 trnaleu_c + 0.10006 trnalys_c + 0.08417 trnamet_c + 0.22764 trnaphe_c + 0.52781 trnapro_c + 0.22288 trnaser_c + 0.40446 trnathr_c + 0.00424 trnatrp_c + 0.11753 trnatyr_c + 0.3637 trnaval_c
Objectif actuel:
 Maximize
1.0*BIOMASS - 1.0*BIOMASS_reverse_69053

In [12]:
model_ralsto.summary()

### 4. Mise à zéro de toutes les réactions d'echanges du modèle

In [13]:
# Afficher les 5 premiers échanges du modèle
print('les 5 premiers échanges: ',model_ralsto.exchanges[:5])
# Mise à zéro de toutes les réactions d'échanges du modèle
for reaction in model_ralsto.exchanges:
    reaction.lower_bound = 0
print('Visualisation des 5 premiers échanges après mise à zéro de lb:')
for rxn in model_ralsto.exchanges[:5]:
    print(f"{rxn.id:30s}  LB = {rxn.lower_bound:8.2f}   UB = {rxn.upper_bound:8.2f}")

les 5 premiers échanges:  [<Reaction EX_hdcea_b at 0x117067920>, <Reaction EX_RSc1944_b at 0x1170679b0>, <Reaction EX_3oochslac_b at 0x117067a70>, <Reaction EX_glu_D_b at 0x117067c80>, <Reaction EX_RipS4_b at 0x117067e90>]
Visualisation des 5 premiers échanges après mise à zéro de lb:
EX_hdcea_b                      LB =     0.00   UB =  1000.00
EX_RSc1944_b                    LB =     0.00   UB =  1000.00
EX_3oochslac_b                  LB =     0.00   UB =  1000.00
EX_glu_D_b                      LB =     0.00   UB =  1000.00
EX_RipS4_b                      LB =     0.00   UB =  1000.00

### 5. Fixation des bornes inférieures et supérieures des réactions d'échanges de métabolites spécifiques

In [14]:
metabolites = ["h2o_b",
               "h_b",
               "k_b",
               "pi_b",
               "na1_b",
               "nh4_b",
               "so4_b",
               "mg2_b",
               "cl_b",
               "fe2_b",
               "fe3_b",
               "cobalt2_b",
               "mn2_b",
               "mobd_b",
               "o2_b",
               "co2_b"]
# Affichage des réactions d'échanges concernées par les métabolites
print("Bornes des réactions d'échanges avant modification:")
for met_id in metabolites:
    exchange_rxn = model_ralsto.reactions.get_by_id(f"EX_{met_id}")
    print(f"{exchange_rxn.id:30s}  LB = {exchange_rxn.lower_bound:8.2f}   UB = {exchange_rxn.upper_bound:8.2f}")

# Fixation des bornes inférieures et supérieures des réactions d'échanges de métabolites spécifiques
print("\nFixation des bornes des réactions d'échanges...")
for met_id in metabolites:
    exchange_rxn = model_ralsto.reactions.get_by_id(f"EX_{met_id}")
    exchange_rxn.lower_bound = -1000  # Autoriser l'importation illimitée
    exchange_rxn.upper_bound = 1000   # Autoriser l'exportation illimitée
# Affichage des réactions d'échanges concernées par les métabolites après modification
print("Bornes des réactions d'échanges après modification:")
for met_id in metabolites:
    exchange_rxn = model_ralsto.reactions.get_by_id(f"EX_{met_id}")
    print(f"{exchange_rxn.id:30s}  LB = {exchange_rxn.lower_bound:8.2f}   UB = {exchange_rxn.upper_bound:8.2f}")

Bornes des réactions d'échanges avant modification:
EX_h2o_b                        LB =     0.00   UB =  1000.00
EX_h_b                          LB =     0.00   UB =  1000.00
EX_k_b                          LB =     0.00   UB =  1000.00
EX_pi_b                         LB =     0.00   UB =  1000.00
EX_na1_b                        LB =     0.00   UB =  1000.00
EX_nh4_b                        LB =     0.00   UB =  1000.00
EX_so4_b                        LB =     0.00   UB =  1000.00
EX_mg2_b                        LB =     0.00   UB =  1000.00
EX_cl_b                         LB =     0.00   UB =  1000.00
EX_fe2_b                        LB =     0.00   UB =  1000.00
EX_fe3_b                        LB =     0.00   UB =  1000.00
EX_cobalt2_b                    LB =     0.00   UB =  1000.00
EX_mn2_b                        LB =     0.00   UB =  1000.00
EX_mobd_b                       LB =     0.00   UB =  1000.00
EX_o2_b                         LB =     0.00   UB =  1000.00
EX_co2_b                        LB =     0.00   UB =  1000.00

Fixation des bornes des réactions d'échanges...
Bornes des réactions d'échanges après modification:
EX_h2o_b                        LB = -1000.00   UB =  1000.00
EX_h_b                          LB = -1000.00   UB =  1000.00
EX_k_b                          LB = -1000.00   UB =  1000.00
EX_pi_b                         LB = -1000.00   UB =  1000.00
EX_na1_b                        LB = -1000.00   UB =  1000.00
EX_nh4_b                        LB = -1000.00   UB =  1000.00
EX_so4_b                        LB = -1000.00   UB =  1000.00
EX_mg2_b                        LB = -1000.00   UB =  1000.00
EX_cl_b                         LB = -1000.00   UB =  1000.00
EX_fe2_b                        LB = -1000.00   UB =  1000.00
EX_fe3_b                        LB = -1000.00   UB =  1000.00
EX_cobalt2_b                    LB = -1000.00   UB =  1000.00
EX_mn2_b                        LB = -1000.00   UB =  1000.00
EX_mobd_b                       LB = -1000.00   UB =  1000.00
EX_o2_b                         LB = -1000.00   UB =  1000.00
EX_co2_b                        LB = -1000.00   UB =  1000.00

### 6. Pourquoi fixer les bornes inférieures des réactions d'échanges sauf pour les réactions faisant intervenir certains métabolites ?

On fixe les bornes inférieures des réactions d'échanges pour simuler un environnement contrôlé où certains métabolites sont disponibles pour l'organisme, tandis que d'autres ne le sont pas. En fixant la borne inférieure à zéro pour la plupart des échanges, on **empêche l'importation de ces métabolites**, ce qui reflète une condition de croissance spécifique. 
Dans notre cas, nous avons fixé la lowerbound de toutes les réactions exchanges à zéro. L'import de tout métabolite est donc impossible. Ensuite, nous avons autorisé l'import de certains métabolites essentiels (glucose, ammonium, phosphate, sulfate, oxygène) en fixant leur lowerbound à une valeur négative. Cela permet à l'organisme de croître en utilisant ces nutriments spécifiques, simulant ainsi un environnement où seuls ces métabolites sont disponibles pour la croissance et le métabolisme de Ralstonia solanacearum.

### 7. Fixation des flux des réactions d'échanges 
- NGAME: 8.39 (réaction correspondant à un flux de consommation d’ATP correspondant à une maintenance de la cellule)

In [15]:
# Visualisation de la réaction NGAME
reaction1 = model_ralsto.reactions.get_by_id("NGAME")
reaction1 # lb = 0 ub = 99999.0 initialement

In [16]:
reaction1.lower_bound = 8.39
reaction1.upper_bound = 8.39
reaction1  # lb = 8.39 ub = 8.39 après modification

- FEOXpp : 0.0 (cette réaction quand elle est active peut amener à produire de l’ATP “gratuitement”)

In [17]:
reaction2 = model_ralsto.reactions.get_by_id("FEOXpp")
reaction2  # lb = 0 ub = 99999.0 initialement

In [18]:
reaction2.lower_bound = 0.0
reaction2.upper_bound = 0.0
reaction2  # lb = 0.0 ub = 0.0 après modification

### 8. Calcul du taux de croissance

In [19]:
# s'assurer que l'objectif est bien la biomasse
model_ralsto.objective = model_ralsto.reactions.get_by_id("BIOMASS")
print("Objectif actuel:\n",model_ralsto.objective)

Objectif actuel:
 Maximize
1.0*BIOMASS - 1.0*BIOMASS_reverse_69053

In [20]:
# Calcul du taux de croissance
solution = model_ralsto.optimize()
print("Taux de croissance optimal (biomass flux): ", solution.objective_value)

Taux de croissance optimal (biomass flux):  0.0

/Users/samngbain/Documents/Master_Bioinformatique/M2/S3/projet_metabolisme/.cobraenv/lib/python3.12/site-packages/cobra/util/solver.py:554: UserWarning: Solver status is 'infeasible'.
  warn(f"Solver status is '{status}'.", UserWarning)

Ce résultat est cohérent car on a mis toutes les réactions d'échanges à zéro, donc pas de nutriments pour la croissance.
- Métabolites importés, excrétés ne peuvent pas être déterminés dans ces conditions.

In [21]:
# solution
# Le statut de l'optimisation est infeasible car il n'y a pas de nutriments disponibles pour la croissance de l'organisme. En mettant
# On ne peut pas determiner les métabolites importés et exportés dans ces conditions.
# Sinon, on peut utiliser solution.fluxes pour voir les flux des réactions et identifier les échanges.

### 9. Fixation des lower bound et upper bound des réactions d'échanges de certains métabolites

- glu_L_b: -8.25

In [22]:
glu_L_b = model_ralsto.reactions.get_by_id("EX_glu_L_b")
print("Flux de la réaction d'échange (glu_L_b): ", glu_L_b.lower_bound) # glu_L_b: 0
### 9. Fixation des lower bound et upper bound des réactions d'échanges de certains métabolites
glu_L_b.lower_bound = -8.25
print("Flux de la réaction d'échange (glu_L_b): ", glu_L_b.lower_bound)

Flux de la réaction d'échange (glu_L_b):  0
Flux de la réaction d'échange (glu_L_b):  -8.25

- 3ohpame_b:  1.5E-4

In [23]:
ohpame_b = model_ralsto.reactions.get_by_id("EX_3ohpame_b")
print("Flux de la réaction d'échange (3ohpame_b): ", ohpame_b.lower_bound) # 3ohpame_b: 0
### 9. Fixation des lower bound et upper bound des réactions d'échanges de certains métabolites
ohpame_b.lower_bound = 1.5e-4
print("Flux de la réaction d'échange (3ohpame_b): ", ohpame_b.lower_bound)

Flux de la réaction d'échange (3ohpame_b):  0
Flux de la réaction d'échange (3ohpame_b):  0.00015

- EPS_b: 0.0062

In [24]:
EPS_b = model_ralsto.reactions.get_by_id("EX_EPS_b")
print("Flux de la réaction d'échange (EPS_b): ", EPS_b.lower_bound) # EPS_b: 0
### 9. Fixation des lower bound et upper bound des réactions d'échanges de certains métabolites
EPS_b.lower_bound = 0.0062
print("Flux de la réaction d'échange (EPS_b): ", EPS_b.lower_bound)

Flux de la réaction d'échange (EPS_b):  0
Flux de la réaction d'échange (EPS_b):  0.0062

- ptrc_b: 0.28

In [25]:
ptrc_b = model_ralsto.reactions.get_by_id("EX_ptrc_b")
print("Flux de la réaction d'échange (ptrc_b): ", ptrc_b.lower_bound) # ptrc_b: 0
### 9. Fixation des lower bound et upper bound des réactions d'échanges de certains métabolites
ptrc_b.lower_bound = 0.28
print("Flux de la réaction d'échange (ptrc_b): ", ptrc_b.lower_bound)

Flux de la réaction d'échange (ptrc_b):  0
Flux de la réaction d'échange (ptrc_b):  0.28

- Tek_28kd_b: 2.7E-4

In [26]:
tek_28kd_b = model_ralsto.reactions.get_by_id("EX_Tek_28kd_b")
print("Flux de la réaction d'échange (Tek_28kd_b): ", tek_28kd_b.lower_bound) # Tek_28kd_b: 0
### 9. Fixation des lower bound et upper bound des réactions d'échanges de certains métabolites
tek_28kd_b.lower_bound = 2.7e-4
print("Flux de la réaction d'échange (Tek_28kd_b): ", tek_28kd_b.lower_bound)

Flux de la réaction d'échange (Tek_28kd_b):  0
Flux de la réaction d'échange (Tek_28kd_b):  0.00027

- etle_b: 0.0129

In [27]:
etle_b = model_ralsto.reactions.get_by_id("EX_etle_b")
print("Flux de la réaction d'échange (etle_b): ", etle_b.lower_bound) # etle_b: 0
### 9. Fixation des lower bound et upper bound des réactions d'échanges de certains métabolites
etle_b.lower_bound = 0.0129
print("Flux de la réaction d'échange (etle_b): ", etle_b.lower_bound)

Flux de la réaction d'échange (etle_b):  0
Flux de la réaction d'échange (etle_b):  0.0129

In [28]:
# Taux de croissance après modification des échanges
solution = model_ralsto.optimize()
print(f"Taux de croissance optimal (biomass flux) après modification des échanges: {solution.objective_value}")

Taux de croissance optimal (biomass flux) après modification des échanges: 0.5119279935101653

La fixation de ces flux permet de simuler un environnement où Ralstonia solanacearum peut importer et exporter certains métabolites essentiels à sa croissance et à son métabolisme. En fixant des valeurs spécifiques pour ces échanges, on observe une augmentation significative du taux de croissance, indiquant que ces métabolites jouent un rôle crucial dans le soutien des fonctions biologiques de l'organisme.
En général, les métabolites externes importés:
- Glucose (EX_glc__D_b)
- Oxygène (EX_o2_b)
- Ammonium (EX_nh4_b)
- Phosphate (EX_pi_b)
- Sulfate (EX_so4_b)
- Eau (EX_h2o_b)
permettent à l'organisme de croître et de produire de la biomasse.

### 10. Calcul du flux de la réaction NGAME pour atteindre un taux de croissance de 0.28 h-1

In [29]:
solution.objective_value

0.5119279935101653

In [30]:
ngame = reaction1
### 10. Calcul du flux de la réaction NGAME pour atteindre un taux de croissance de 0.28 h-1
growth_target = 0.28
biomass_rxn.bounds = (growth_target, growth_target)
model_ralsto.objective = ngame
solution = model_ralsto.optimize(objective_sense='min')
solution.fluxes[ngame.id]

np.float64(8.39)

Le taux de croissance de 0.28 h-1 est atteint lorsque le flux de la réaction NGAME est fixé à 64.76. Cela indique que pour soutenir une croissance optimale, Ralstonia solanacearum nécessite un certain niveau de consommation d'ATP pour la maintenance cellulaire, reflété par le flux de NGAME.

- Sauvegarde des valeurs de flux

In [33]:
model_ralsto.compartments

{'b': 'boundary', 'e': 'extracellular', 'c': 'cytoplasm', 'p': 'periplasm'}

In [34]:
import pandas as pd

# Fixer NGAME
ngame = model_ralsto.reactions.get_by_id("NGAME")
ngame.bounds = (64.76, 64.76)

# Optimiser le modèle
solution = model_ralsto.optimize()

# Préparer les flux pour export
flux_dict = {}
for rxn in model_ralsto.reactions:
    flux_dict["R_" + rxn.id ] = solution.fluxes[rxn.id]  # ajouter préfixe R_

# Convertir en DataFrame
flux_df = pd.DataFrame(list(flux_dict.items()), columns=["Reaction", "Flux"])


# **Filtrer les flux nuls**
# flux_df = flux_df[flux_df["Flux"] != 0]

# Supprimer les réactions d'echanges
# flux_df = flux_df[~flux_df["Reaction"].str.startswith("R_EX_")]


# Sauver dans un fichier tabulé (TSV)
flux_df.to_csv("fluxes_Ralstonia_glycolysis.tsv", sep="\t", index=False)

print("Flux exportés dans fluxes_Ralstonia_glycolysis.tsv")

Flux exportés dans fluxes_Ralstonia_glycolysis.tsv